# /etc/fail2ban/jail.d/fileshare.conf
[fileshare]
enabled  = true
backend  = systemd
filter   = fileshare
maxretry = 20
findtime = 600
bantime  = 3600
action   = %(banaction)s[name=%(__name__)s, port="http,https", protocol="%(protocol)s", chain="%(chain)s"]
